# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Reales Brillantes Santiago
email: contacto@santiago.realesbrillantes.cl
description: > # this means to ignore newlines until "baseurl:"
  Reales Brillantes Santiago, filial de Caporales Reales Brillantes Andino. 
  Asociacióm Cultural, Folclórica, Juvenil, Deportiva y Social que promueve el desarrollo de las danzas y cultura andina, en especial el caporal.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://santiago.realesbrillantes.cl" # the base hostname & protocol for your site
twitter_username: rbstgo

# Build settings
markdown: kramdown

exclude: ['node_modules',‘css’, ‘_scss’]
keep_files: ['_site/css', 'css']
include: ['_sass']

languages: ["es"]
exclude_from_localizations: ["js", "images", "css", "icons","node_modules"]

defaults:
  - scope:
      path: "/socios/reglamentos/"
      type: regulations
    values:
      layout: regulations

collections:
  news:
    foo: bar
  regulations:
    output: true
  events:
    foo: bar
    presentation_date: "2016-01-01"
    place: "TBD"
    start_date: "2016-01-01"
